In [1]:
import pandas as pd
import ast

In [2]:
matches = pd.read_csv('../data/raw/matches_1930_2022.csv')

matches.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

In [3]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    str
 1   away_team                        964 non-null    str
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    str
 9   home_captain                     644 non-null    str
 10  away_manager                     964 non-null    str
 11  away_captain                     644 non-null    str
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    str
 14  Officials                        709 non-null    str
 15  Round                            964 non-null    str
 16  Date                             964 non-null    str
 17  Score                            964 non-null    str
 18  Referee                          709 non-null    str
 19  Notes                            73 non-null     str
 20  Host                             964 non-null    str
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    str
 23  away_goal                        571 non-null    str
 24  home_goal_long                   718 non-null    str
 25  away_goal_long                   571 non-null    str
 26  home_own_goal                    39 non-null     str
 27  away_own_goal                    17 non-null     str
 28  home_penalty_goal                116 non-null    str
 29  away_penalty_goal                84 non-null     str
 30  home_penalty_miss_long           6 non-null      str
 31  away_penalty_miss_long           9 non-null      str
 32  home_penalty_shootout_goal_long  34 non-null     str
 33  away_penalty_shootout_goal_long  34 non-null     str
 34  home_penalty_shootout_miss_long  24 non-null     str
 35  away_penalty_shootout_miss_long  30 non-null     str
 36  home_red_card                    51 non-null     str
 37  away_red_card                    54 non-null     str
 38  home_yellow_red_card             23 non-null     str
 39  away_yellow_red_card             31 non-null     str
 40  home_yellow_card_long            621 non-null    str
 41  away_yellow_card_long            627 non-null    str
 42  home_substitute_in_long          740 non-null    str
 43  away_substitute_in_long          747 non-null    str
dtypes: float64(4), int64(4), str(36)
memory usage: 331.5 KB

In [4]:
matches ['Date'] = pd.to_datetime(matches['Date'], format = '%Y-%m-%d', errors = 'coerce')

#Transformando a coluna 'Date' para o formato datetime, utilizando o formato específico de data e tratando erros de conversão.

In [5]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    str
 1   away_team                        964 non-null    str
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    str
 9   home_captain                     644 non-null    str
 10  away_manager                     964 non-null    str
 11  away_captain                     644 non-null    str
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    str
 14  Officials                        709 non-null    str
 15  Round                            964 non-null    str
 16  Date                             964 non-null    datetime64[us]
 17  Score                            964 non-null    str
 18  Referee                          709 non-null    str
 19  Notes                            73 non-null     str
 20  Host                             964 non-null    str
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    str
 23  away_goal                        571 non-null    str
 24  home_goal_long                   718 non-null    str
 25  away_goal_long                   571 non-null    str
 26  home_own_goal                    39 non-null     str
 27  away_own_goal                    17 non-null     str
 28  home_penalty_goal                116 non-null    str
 29  away_penalty_goal                84 non-null     str
 30  home_penalty_miss_long           6 non-null      str
 31  away_penalty_miss_long           9 non-null      str
 32  home_penalty_shootout_goal_long  34 non-null     str
 33  away_penalty_shootout_goal_long  34 non-null     str
 34  home_penalty_shootout_miss_long  24 non-null     str
 35  away_penalty_shootout_miss_long  30 non-null     str
 36  home_red_card                    51 non-null     str
 37  away_red_card                    54 non-null     str
 38  home_yellow_red_card             23 non-null     str
 39  away_yellow_red_card             31 non-null     str
 40  home_yellow_card_long            621 non-null    str
 41  away_yellow_card_long            627 non-null    str
 42  home_substitute_in_long          740 non-null    str
 43  away_substitute_in_long          747 non-null    str
dtypes: datetime64[us](1), float64(4), int64(4), str(35)
memory usage: 331.5 KB

In [6]:
print(matches['Round'].value_counts())

# Contagem dos valores únicos na coluna 'Round', que indica as fases do torneio, 
# para entender a distribuição dos jogos em diferentes etapas da competição.

Round
Group stage             587
Round of 16              97
Quarter-finals           70
First round              48
Semi-finals              38
First group stage        36
Second round             24
Final                    21
Third-place match        20
Second group stage       12
Final stage               6
Group stage play-off      5
Name: count, dtype: int64

In [7]:
fase_map = {
    'group stage': 'Fase de Grupos',
    'round of 16': 'Oitavas de Final',
    'quarter-finals': 'Quartas de Final',
    'semi-finals': 'Semi-finais',
    'final': 'Final',
    'third-place match': 'Terceiro Lugar',
    'first round': 'Fase de Grupos',
    'first group stage': 'Fase de Grupos',
    'second round': 'Fase de Grupos',
    'second group stage': 'Fase de Grupos',
    'group stage play-off': 'Fase de Grupos',
    'final stage': 'Fase de Grupos'}

In [8]:
matches ['Stage'] =  (matches['Round'].str.lower().str.strip().map(fase_map))

#Criando uma nova coluna 'Stage' mapeando os valores da coluna 'Round' para categorias mais amplas, 
# utilizando um dicionário de mapeamento para agrupar as fases do torneio em categorias como 'Fase de Grupos', 
# 'Oitavas de Final', etc.

In [9]:
matches ['Stage'].value_counts()

Stage
Fase de Grupos      718
Oitavas de Final     97
Quartas de Final     70
Semi-finais          38
Final                21
Terceiro Lugar       20
Name: count, dtype: int64

In [10]:
matches['Stage'].describe()

count                964
unique                 6
top       Fase de Grupos
freq                 718
Name: Stage, dtype: object

In [11]:
def get_winner(row):
    if pd.notna(row['home_penalty']) and pd.notna(row['away_penalty']):
        if row['home_penalty'] > row['away_penalty']:
            return row['home_team']
        elif row['home_penalty'] < row['away_penalty']:
            return row['away_team']
        else:
            return 'Draw'
    elif row['home_score'] > row['away_score']:
        return row['home_team']
    elif row['home_score'] < row['away_score']:
        return row['away_team']
    else:
        return 'Draw'
    

#Função para determinar o vencedor de cada partida, considerando tanto o resultado do tempo normal quanto os pênaltis, e retornando o nome do time vencedor ou 'Draw' em caso de empate.

In [12]:
matches ['Winner'] = matches.apply(get_winner, axis=1  )

In [13]:
matches [matches['Year'] == 2022][['home_team', 'away_team', 'home_score', 'away_score', 'home_penalty', 'away_penalty', 'Winner', 'Stage']].head()

,home_team,away_team,home_score,away_score,home_penalty,away_penalty,Winner,Stage
0,Argentina,France,3,3,4.0,2.0,Argentina,Final
1,Croatia,Morocco,2,1,NaN,NaN,Croatia,Terceiro Lugar
2,France,Morocco,2,0,NaN,NaN,France,Semi-finais
3,Argentina,Croatia,3,0,NaN,NaN,Argentina,Semi-finais
4,Morocco,Portugal,1,0,NaN,NaN,Morocco,Quartas de Final

In [14]:
matches [['home_red_card', 'away_red_card', 'home_yellow_red_card', 'away_yellow_red_card', 'home_yellow_card_long', 'away_yellow_card_long']].head()

,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long
0,NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2..."
1,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;..."
2,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal']
3,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0..."
4,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha']

In [15]:
def count_cards(row):
    if pd.isna(row):
        0
    try: 
        eventos = ast.literal_eval(str(row))
        return len(eventos)
    except: 
        return 0
    
#Função para contar o número de cartões em uma célula, 
# tratando valores ausentes e convertendo strings que representam listas de eventos em objetos Python 
# para contar corretamente o número de cartões.

In [16]:
def count_red_cards(x):
    if pd.isna(x) or str(x).strip() == '':
        return 0
    
    return str(x).count('|') + 1

In [17]:
matches ['h_yellow_card_long_count'] = matches['home_yellow_card_long'].apply(count_cards)

matches ['a_yellow_card_long_count'] = matches['away_yellow_card_long'].apply(count_cards)

In [18]:
matches['h_red_card_count'] = (
    matches['home_red_card']
    .apply(count_red_cards)
)

matches['a_red_card_count'] = (
    matches['away_red_card']
    .apply(count_red_cards)
)

In [19]:
matches['h_yellow_red_card_count'] = (
    matches['home_yellow_red_card']
    .apply(count_red_cards)
)

matches['a_yellow_red_card_count'] = (
    matches['away_yellow_red_card']
    .apply(count_red_cards)
)

In [20]:
matches [['h_yellow_card_long_count', 'a_yellow_card_long_count','h_red_card_count', 'a_red_card_count', 'h_yellow_red_card_count', 'a_yellow_red_card_count']].head(50)

,h_yellow_card_long_count,a_yellow_card_long_count,h_red_card_count,a_red_card_count,h_yellow_red_card_count,a_yellow_red_card_count
0,5,3,0,0,0,0
1,0,2,0,0,0,0
2,0,1,0,0,0,0
3,2,2,0,0,0,0
4,2,1,0,0,1,0
5,1,3,0,0,0,0
6,2,3,0,0,0,0
7,7,10,0,0,1,0
8,1,1,0,0,0,0
9,0,2,0,0,0,0
10,0,2,0,0,0,0
11,0,1,0,0,0,0
12,1,2,0,0,0,0
13,0,1,0,0,0,0
14,2,0,0,0,0,0
15,0,2,0,0,0,0
16,2,0,0,0,0,0
17,2,5,0,0,0,0
18,4,2,0,0,1,0
19,7,4,0,0,0,0
20,4,0,0,0,0,0
21,0,1,0,0,0,0
22,1,0,0,0,0,0
23,3,0,0,0,0,0
24,2,1,0,0,0,0
25,1,0,0,0,0,0
26,6,1,0,0,0,0
27,1,1,0,0,0,0
28,0,1,0,0,0,0
29,1,0,0,0,0,0
30,3,1,0,0,0,0
31,2,0,0,0,0,0
32,2,2,0,0,0,0
33,2,2,1,0,0,0
34,1,1,0,0,0,0
35,3,2,0,0,0,0
36,3,3,0,0,0,0
37,1,1,0,0,0,0
38,2,2,0,0,0,0
39,1,3,0,0,0,0
40,3,0,0,0,0,0
41,3,2,0,0,0,0
42,1,2,0,0,0,0
43,1,4,0,0,0,0
44,1,2,1,0,0,0
45,3,3,0,0,0,0
46,0,1,0,0,0,0
47,0,0,0,0,0,0
48,2,1,0,0,0,0
49,1,2,0,0,0,0

In [28]:
matches[
    matches['h_yellow_red_card_count'] > 0
][
    ['home_team', 'home_yellow_red_card', 'h_yellow_red_card_count']
].head(5)

       home_team      home_yellow_red_card  h_yellow_red_card_count
4        Morocco     Walid Cheddira · 90+3                        1
7    Netherlands   Denzel Dumfries · 120+3                        1
18      Cameroon  Vincent Aboubakar · 90+3                        1
101      Germany       Jérôme Boateng · 82                        1
141   Costa Rica         Óscar Duarte · 66                        1

In [25]:
matches[
    matches['a_red_card_count'] > 0
][
    ['away_team', 'away_red_card', 'a_red_card_count']
].head(5)

       away_team        away_red_card  a_red_card_count
72   Switzerland  Michael Lang · 90+3                 1
146      Belgium   Steven Defour · 44                 1
178     Portugal            Pepe · 37                 1
201     Portugal   Ricardo Costa · 89                 1
231    Australia    Harry Kewell · 24                 1

In [30]:
matches[['h_red_card_count', 'a_red_card_count', 'h_yellow_red_card_count', 'a_yellow_red_card_count'  ]].info()

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   h_red_card_count         964 non-null    int64
 1   a_red_card_count         964 non-null    int64
 2   h_yellow_red_card_count  964 non-null    int64
 3   a_yellow_red_card_count  964 non-null    int64
dtypes: int64(4)
memory usage: 30.3 KB

In [31]:
matches['home_red_card'].dropna().head(20)

33        Paulo Bento · 90+11
44       Wayne Hennessey · 86
111        Carlos Sánchez · 3
151     Antonio Valencia · 50
153    Claudio Marchisio · 59
158           Ante Rebić · 89
174            Alex Song · 40
185       Maxi Pereira · 90+4
199       Luis Suárez · 120+1
221       Yoann Gourcuff · 25
255      Nicolás Lodeiro · 81
260         Wayne Rooney · 62
266      Marco Materazzi · 50
295       Tomáš Ujfaluši · 65
296     Daniele De Rossi · 28
330       Rafael Márquez · 88
338           João Pinto · 27
347           Nastja Čeh · 81
366        Thierry Henry · 25
373       Boris Živković · 59
Name: home_red_card, dtype: str

In [ ]:
matches['away_red_card'].dropna().head(20)

In [ ]:
matches[
    [
        'home_yellow_card_long',
        'h_yellow_card_long_count'
    ]
].dropna().head(10)

In [37]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 53 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    str
 1   away_team                        964 non-null    str
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    str
 9   home_captain                     644 non-null    str
 10  away_manager                     964 non-null    str
 11  away_captain                     644 non-null    str
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    str
 14  Officials                        709 non-null    str
 15  Round                            964 non-null    str
 16  Date                             964 non-null    datetime64[us]
 17  Score                            964 non-null    str
 18  Referee                          709 non-null    str
 19  Notes                            73 non-null     str
 20  Host                             964 non-null    str
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    str
 23  away_goal                        571 non-null    str
 24  home_goal_long                   718 non-null    str
 25  away_goal_long                   571 non-null    str
 26  home_own_goal                    39 non-null     str
 27  away_own_goal                    17 non-null     str
 28  home_penalty_goal                116 non-null    str
 29  away_penalty_goal                84 non-null     str
 30  home_penalty_miss_long           6 non-null      str
 31  away_penalty_miss_long           9 non-null      str
 32  home_penalty_shootout_goal_long  34 non-null     str
 33  away_penalty_shootout_goal_long  34 non-null     str
 34  home_penalty_shootout_miss_long  24 non-null     str
 35  away_penalty_shootout_miss_long  30 non-null     str
 36  home_red_card                    51 non-null     str
 37  away_red_card                    54 non-null     str
 38  home_yellow_red_card             23 non-null     str
 39  away_yellow_red_card             31 non-null     str
 40  home_yellow_card_long            621 non-null    str
 41  away_yellow_card_long            627 non-null    str
 42  home_substitute_in_long          740 non-null    str
 43  away_substitute_in_long          747 non-null    str
 44  Stage                            964 non-null    str
 45  Winner                           964 non-null    str
 46  h_yellow_card_long_count         964 non-null    int64
 47  a_yellow_card_long_count         964 non-null    int64
 48  h_red_card_count                 964 non-null    int64
 49  a_red_card_count                 964 non-null    int64
 50  h_yellow_red_card_count          964 non-null    int64
 51  a_yellow_red_card_count          964 non-null    int64
 52  total_goals                      964 non-null    int64
dtypes: datetime64[us](1), float64(4), int64(11), str(37)
memory usage: 399.3 KB

In [ ]:
matches.head(35)

In [34]:
matches['total_goals'] = matches ['home_score'] + matches ['away_score']

In [38]:
matches_clean = matches [['home_team', 'away_team', 'home_score', 'away_score', 'home_penalty', 'away_penalty', 
                          'total_goals', 'Winner', 'Stage', 'Year', 'Date', 'Host', 'Venue', 'Attendance', 'h_red_card_count', 'a_red_card_count', 'h_yellow_red_card_count', 'a_yellow_red_card_count', 
                          'h_yellow_card_long_count', 'a_yellow_card_long_count']]

In [39]:
matches_clean.head(35)

,home_team,away_team,home_score,away_score,home_penalty,away_penalty,total_goals,Winner,Stage,Year,Date,Host,Venue,Attendance,h_red_card_count,a_red_card_count,h_yellow_red_card_count,a_yellow_red_card_count,h_yellow_card_long_count,a_yellow_card_long_count
0,Argentina,France,3,3,4.0,2.0,6,Argentina,Final,2022,2022-12-18,Qatar,"Lusail Iconic Stadium, Lusail",88966,0,0,0,0,5,3
1,Croatia,Morocco,2,1,NaN,NaN,3,Croatia,Terceiro Lugar,2022,2022-12-17,Qatar,"Khalifa International Stadium, Doha",44137,0,0,0,0,0,2
2,France,Morocco,2,0,NaN,NaN,2,France,Semi-finais,2022,2022-12-14,Qatar,"Al Bayt Stadium, Al Khor",68294,0,0,0,0,0,1
3,Argentina,Croatia,3,0,NaN,NaN,3,Argentina,Semi-finais,2022,2022-12-13,Qatar,"Lusail Iconic Stadium, Lusail",88966,0,0,0,0,2,2
4,Morocco,Portugal,1,0,NaN,NaN,1,Morocco,Quartas de Final,2022,2022-12-10,Qatar,"Al Thumama Stadium, ath-Thumāma",44198,0,0,1,0,2,1
5,England,France,1,2,NaN,NaN,3,France,Quartas de Final,2022,2022-12-10,Qatar,"Al Bayt Stadium, Al Khor",68895,0,0,0,0,1,3
6,Croatia,Brazil,1,1,4.0,2.0,2,Croatia,Quartas de Final,2022,2022-12-09,Qatar,"Education City Stadium, Doha",43893,0,0,0,0,2,3
7,Netherlands,Argentina,2,2,3.0,4.0,4,Argentina,Quartas de Final,2022,2022-12-09,Qatar,"Lusail Iconic Stadium, Lusail",88235,0,0,1,0,7,10
8,Morocco,Spain,0,0,3.0,0.0,0,Morocco,Oitavas de Final,2022,2022-12-06,Qatar,"Education City Stadium, Doha",44667,0,0,0,0,1,1
9,Portugal,Switzerland,6,1,NaN,NaN,7,Portugal,Oitavas de Final,2022,2022-12-06,Qatar,"Lusail Iconic Stadium, Lusail",83720,0,0,0,0,0,2
10,Japan,Croatia,1,1,1.0,3.0,2,Croatia,Oitavas de Final,2022,2022-12-05,Qatar,"Al Janoub Stadium, Al Wakrah",42523,0,0,0,0,0,2
11,Brazil,Korea Republic,4,1,NaN,NaN,5,Brazil,Oitavas de Final,2022,2022-12-05,Qatar,"Stadium 974, Doha",43847,0,0,0,0,0,1
12,France,Poland,3,1,NaN,NaN,4,France,Oitavas de Final,2022,2022-12-04,Qatar,"Al Thumama Stadium, ath-Thumāma",40989,0,0,0,0,1,2
13,England,Senegal,3,0,NaN,NaN,3,England,Oitavas de Final,2022,2022-12-04,Qatar,"Al Bayt Stadium, Al Khor",65985,0,0,0,0,0,1
14,Netherlands,United States,3,1,NaN,NaN,4,Netherlands,Oitavas de Final,2022,2022-12-03,Qatar,"Khalifa International Stadium, Doha",44846,0,0,0,0,2,0
15,Argentina,Australia,2,1,NaN,NaN,3,Argentina,Oitavas de Final,2022,2022-12-03,Qatar,"Ahmed bin Ali Stadium, Umm al-Afā'ī",45032,0,0,0,0,0,2
16,Korea Republic,Portugal,2,1,NaN,NaN,3,Korea Republic,Fase de Grupos,2022,2022-12-02,Qatar,"Education City Stadium, Doha",44097,0,0,0,0,2,0
17,Ghana,Uruguay,0,2,NaN,NaN,2,Uruguay,Fase de Grupos,2022,2022-12-02,Qatar,"Al Janoub Stadium, Al Wakrah",43443,0,0,0,0,2,5
18,Cameroon,Brazil,1,0,NaN,NaN,1,Cameroon,Fase de Grupos,2022,2022-12-02,Qatar,"Lusail Iconic Stadium, Lusail",85986,0,0,1,0,4,2
19,Serbia,Switzerland,2,3,NaN,NaN,5,Switzerland,Fase de Grupos,2022,2022-12-02,Qatar,"Stadium 974, Doha",41378,0,0,0,0,7,4
20,Canada,Morocco,1,2,NaN,NaN,3,Morocco,Fase de Grupos,2022,2022-12-01,Qatar,"Al Thumama Stadium, ath-Thumāma",43102,0,0,0,0,4,0
21,Croatia,Belgium,0,0,NaN,NaN,0,Draw,Fase de Grupos,2022,2022-12-01,Qatar,"Ahmed bin Ali Stadium, Umm al-Afā'ī",43984,0,0,0,0,0,1
22,Costa Rica,Germany,2,4,NaN,NaN,6,Germany,Fase de Grupos,2022,2022-12-01,Qatar,"Al Bayt Stadium, Al Khor",67054,0,0,0,0,1,0
23,Japan,Spain,2,1,NaN,NaN,3,Japan,Fase de Grupos,2022,2022-12-01,Qatar,"Khalifa International Stadium, Doha",44851,0,0,0,0,3,0
24,Australia,Denmark,1,0,NaN,NaN,1,Australia,Fase de Grupos,2022,2022-11-30,Qatar,"Al Janoub Stadium, Al Wakrah",41232,0,0,0,0,2,1
25,Tunisia,France,1,0,NaN,NaN,1,Tunisia,Fase de Grupos,2022,2022-11-30,Qatar,"Education City Stadium, Doha",43627,0,0,0,0,1,0
26,Saudi Arabia,Mexico,1,2,NaN,NaN,3,Mexico,Fase de Grupos,2022,2022-11-30,Qatar,"Lusail Iconic Stadium, Lusail",84985,0,0,0,0,6,1
27,Poland,Argentina,0,2,NaN,NaN,2,Argentina,Fase de Grupos,2022,2022-11-30,Qatar,"Stadium 974, Doha",44089,0,0,0,0,1,1
28,Ecuador,Senegal,1,2,NaN,NaN,3,Senegal,Fase de Grupos,2022,2022-11-29,Qatar,"Khalifa International Stadium, Doha",44569,0,0,0,0,0,1
29,Netherlands,Qatar,2,0,NaN,NaN,2,Netherlands,Fase de Grupos,2022,2022-11-29,Qatar,"Al Bayt Stadium, Al Khor",66784,0,0,0,0,1,0
30,IR Iran,United States,0,1,NaN,NaN,1,United States,Fase de Grupos,2022,2022-11-29,Qatar,"Al Thumama Stadium, ath-Thumāma",42127,0,0,0,0,3,1
31,Wales,England,0,3,NaN,NaN,3,England,Fase de Grupos,2022,2022-11-29,Qatar,"Ahmed bin Ali Stadium, Umm al-Afā'ī",44297,0,0,0,0,2,0
32,Cameroon,Serbia,3,3,NaN,NaN,6,Draw,Fase de Grupos,2022,2022-11-28,Qatar,"Al Janoub Stadium, Al Wakrah",39789,0,0,0,0,2,2
33,Korea Republic,Ghana,2,3,NaN,NaN,5,Ghana,Fase de Grupos,2022,2022-11-28,Qatar,"Education City Stadium, Doha",43983,1,0,0,0,2,2
34,Brazil,Switzerland,1,0,NaN,NaN,1,Brazil,Fase de Grupos,2022,2022-11-28,Qatar,"Stadium 974, Doha",43649,0,0,0,0,1,1

In [43]:
matches_clean.to_csv('../data/processed/matches_clean.csv', index=True)