In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv('data/matches_1930_2022.csv')
matches.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

In [4]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    str
 1   away_team                        964 non-null    str
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    str
 9   home_captain                     644 non-null    str
 10  away_manager                     964 non-null    str
 11  away_captain                     644 non-null    str
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    str
 14  Officials                        709 non-null    str
 15  Round                            964 non-null    str
 16  Date                             964 non-null    str
 17  Score                            964 non-null    str
 18  Referee                          709 non-null    str
 19  Notes                            73 non-null     str
 20  Host                             964 non-null    str
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    str
 23  away_goal                        571 non-null    str
 24  home_goal_long                   718 non-null    str
 25  away_goal_long                   571 non-null    str
 26  home_own_goal                    39 non-null     str
 27  away_own_goal                    17 non-null     str
 28  home_penalty_goal                116 non-null    str
 29  away_penalty_goal                84 non-null     str
 30  home_penalty_miss_long           6 non-null      str
 31  away_penalty_miss_long           9 non-null      str
 32  home_penalty_shootout_goal_long  34 non-null     str
 33  away_penalty_shootout_goal_long  34 non-null     str
 34  home_penalty_shootout_miss_long  24 non-null     str
 35  away_penalty_shootout_miss_long  30 non-null     str
 36  home_red_card                    51 non-null     str
 37  away_red_card                    54 non-null     str
 38  home_yellow_red_card             23 non-null     str
 39  away_yellow_red_card             31 non-null     str
 40  home_yellow_card_long            621 non-null    str
 41  away_yellow_card_long            627 non-null    str
 42  home_substitute_in_long          740 non-null    str
 43  away_substitute_in_long          747 non-null    str
dtypes: float64(4), int64(4), str(36)
memory usage: 331.5 KB

In [5]:
matches ['Date'] = pd.to_datetime(matches['Date'], format = '%Y-%m-%d', errors = 'coerce')

In [6]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    str
 1   away_team                        964 non-null    str
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    str
 9   home_captain                     644 non-null    str
 10  away_manager                     964 non-null    str
 11  away_captain                     644 non-null    str
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    str
 14  Officials                        709 non-null    str
 15  Round                            964 non-null    str
 16  Date                             964 non-null    datetime64[us]
 17  Score                            964 non-null    str
 18  Referee                          709 non-null    str
 19  Notes                            73 non-null     str
 20  Host                             964 non-null    str
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    str
 23  away_goal                        571 non-null    str
 24  home_goal_long                   718 non-null    str
 25  away_goal_long                   571 non-null    str
 26  home_own_goal                    39 non-null     str
 27  away_own_goal                    17 non-null     str
 28  home_penalty_goal                116 non-null    str
 29  away_penalty_goal                84 non-null     str
 30  home_penalty_miss_long           6 non-null      str
 31  away_penalty_miss_long           9 non-null      str
 32  home_penalty_shootout_goal_long  34 non-null     str
 33  away_penalty_shootout_goal_long  34 non-null     str
 34  home_penalty_shootout_miss_long  24 non-null     str
 35  away_penalty_shootout_miss_long  30 non-null     str
 36  home_red_card                    51 non-null     str
 37  away_red_card                    54 non-null     str
 38  home_yellow_red_card             23 non-null     str
 39  away_yellow_red_card             31 non-null     str
 40  home_yellow_card_long            621 non-null    str
 41  away_yellow_card_long            627 non-null    str
 42  home_substitute_in_long          740 non-null    str
 43  away_substitute_in_long          747 non-null    str
dtypes: datetime64[us](1), float64(4), int64(4), str(35)
memory usage: 331.5 KB

In [7]:
print(matches['Round'].value_counts())

Round
Group stage             587
Round of 16              97
Quarter-finals           70
First round              48
Semi-finals              38
First group stage        36
Second round             24
Final                    21
Third-place match        20
Second group stage       12
Final stage               6
Group stage play-off      5
Name: count, dtype: int64

In [8]:
fase_map = {
    'group stage': 'Fase de Grupos',
    'round of 16': 'Oitavas de Final',
    'quarter-finals': 'Quartas de Final',
    'semi-finals': 'Semi-finais',
    'final': 'Final',
    'third-place match': 'Terceiro Lugar',
    'first round': 'Fase de Grupos',
    'first group stage': 'Fase de Grupos',
    'second round': 'Fase de Grupos',
    'second group stage': 'Fase de Grupos',
    'group stage play-off': 'Fase de Grupos',
    'final stage': 'Fase de Grupos'}

In [9]:
matches ['Stage'] = matches['Round'].str.lower().map(fase_map)

In [10]:
matches ['Stage'].value_counts()

Stage
Fase de Grupos      718
Oitavas de Final     97
Quartas de Final     70
Semi-finais          38
Final                21
Terceiro Lugar       20
Name: count, dtype: int64

In [11]:
matches['Stage'].describe()

count                964
unique                 6
top       Fase de Grupos
freq                 718
Name: Stage, dtype: object

In [12]:
def get_winner(row):
    if pd.notna(row['home_penalty']) and pd.notna(row['away_penalty']):
        if row['home_penalty'] > row['away_penalty']:
            return row['home_team']
        elif row['home_penalty'] < row['away_penalty']:
            return row['away_team']
        else:
            return 'Draw'
    elif row['home_score'] > row['away_score']:
        return row['home_team']
    elif row['home_score'] < row['away_score']:
        return row['away_team']
    else:
        return 'Draw'

In [13]:
matches ['Winner'] = matches.apply(get_winner, axis=1  )

In [14]:
matches [matches['Year'] == 2022][['home_team', 'away_team', 'home_score', 'away_score', 'home_penalty', 'away_penalty', 'Winner', 'Stage']].head()

,home_team,away_team,home_score,away_score,home_penalty,away_penalty,Winner,Stage
0,Argentina,France,3,3,4.0,2.0,Argentina,Final
1,Croatia,Morocco,2,1,NaN,NaN,Croatia,Terceiro Lugar
2,France,Morocco,2,0,NaN,NaN,France,Semi-finais
3,Argentina,Croatia,3,0,NaN,NaN,Argentina,Semi-finais
4,Morocco,Portugal,1,0,NaN,NaN,Morocco,Quartas de Final

In [15]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 46 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    str
 1   away_team                        964 non-null    str
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    str
 9   home_captain                     644 non-null    str
 10  away_manager                     964 non-null    str
 11  away_captain                     644 non-null    str
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    str
 14  Officials                        709 non-null    str
 15  Round                            964 non-null    str
 16  Date                             964 non-null    datetime64[us]
 17  Score                            964 non-null    str
 18  Referee                          709 non-null    str
 19  Notes                            73 non-null     str
 20  Host                             964 non-null    str
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    str
 23  away_goal                        571 non-null    str
 24  home_goal_long                   718 non-null    str
 25  away_goal_long                   571 non-null    str
 26  home_own_goal                    39 non-null     str
 27  away_own_goal                    17 non-null     str
 28  home_penalty_goal                116 non-null    str
 29  away_penalty_goal                84 non-null     str
 30  home_penalty_miss_long           6 non-null      str
 31  away_penalty_miss_long           9 non-null      str
 32  home_penalty_shootout_goal_long  34 non-null     str
 33  away_penalty_shootout_goal_long  34 non-null     str
 34  home_penalty_shootout_miss_long  24 non-null     str
 35  away_penalty_shootout_miss_long  30 non-null     str
 36  home_red_card                    51 non-null     str
 37  away_red_card                    54 non-null     str
 38  home_yellow_red_card             23 non-null     str
 39  away_yellow_red_card             31 non-null     str
 40  home_yellow_card_long            621 non-null    str
 41  away_yellow_card_long            627 non-null    str
 42  home_substitute_in_long          740 non-null    str
 43  away_substitute_in_long          747 non-null    str
 44  Stage                            964 non-null    str
 45  Winner                           964 non-null    str
dtypes: datetime64[us](1), float64(4), int64(4), str(37)
memory usage: 346.6 KB

In [16]:
def conta_cartao(x):
    if pd.isna(x):
        return 0
    else:
        return str(x).count('|') + 1

In [17]:
matches['home_red_cards'] = matches['home_red_card'].apply(conta_cartao)
matches['away_red_cards'] = matches['away_red_card'].apply(conta_cartao)
matches['home_yellow_red_cards'] = matches['home_yellow_red_card'].apply(conta_cartao)
matches['away_yellow_red_cards'] = matches['away_yellow_red_card'].apply(conta_cartao)

In [18]:
# Verifica
print(matches['home_red_cards'].value_counts())
print(matches['away_red_cards'].value_counts())

home_red_cards
0    913
1     50
2      1
Name: count, dtype: int64
away_red_cards
0    910
1     46
2      8
Name: count, dtype: int64

In [19]:
print(matches['away_yellow_red_cards'].value_counts())
print(matches['home_yellow_red_cards'].value_counts())

away_yellow_red_cards
0    933
1     29
2      2
Name: count, dtype: int64
home_yellow_red_cards
0    941
1     21
2      2
Name: count, dtype: int64

In [20]:
matches.head(35)

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long,Stage,Winner,home_red_cards,away_red_cards,home_yellow_red_cards,away_yellow_red_cards
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...,Final,Argentina,0,0,0,0
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...,Terceiro Lugar,Croatia,0,0,0,0
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...,Semi-finais,France,0,0,0,0
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',...",Semi-finais,Argentina,0,0,0,0
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...,Quartas de Final,Morocco,0,0,1,0
5,England,France,1,2.4,NaN,2,0.9,NaN,Gareth Southgate,Harry Kane,...,['90&rsquor;|1:2|Harry Maguire'],"['43&rsquor;|0:1|Antoine Griezmann', '47&rsquo...",['79&rsquor;|1:2|Raheem Sterling|for Bukayo Sa...,['79&rsquor;|1:2|Kingsley Coman|for Ousmane De...,Quartas de Final,France,0,0,0,0
6,Croatia,Brazil,1,0.6,4.0,1,2.5,2.0,Zlatko Dalić,Luka Modrić,...,"['31&rsquor;|0:0|Marcelo Brozović', '117&rsquo...","['25&rsquor;|0:0|Danilo', '68&rsquor;|0:0|Case...",['72&rsquor;|0:0|Nikola Vlašić|for Mario Pašal...,"['56&rsquor;|0:0|Antony|for Raphinha', '64&rsq...",Quartas de Final,Croatia,0,0,0,0
7,Netherlands,Argentina,2,0.6,3.0,2,1.9,4.0,Louis van Gaal,Virgil van Dijk,...,"['43&rsquor;|0:1|Jurriën Timber', '45+2&rsquor...","['31&rsquor;|0:0|Walter Samuel', '43&rsquor;|0...",['46&rsquor;|0:1|Steven Berghuis|for Steven Be...,['66&rsquor;|0:1|Leandro Paredes|for Rodrigo D...,Quartas de Final,Argentina,0,0,1,0
8,Morocco,Spain,0,0.7,3.0,0,1.0,0.0,Hoalid Regragui,Romain Saïss,...,['90&rsquor;|0:0|Romain Saïss'],['77&rsquor;|0:0|Aymeric Laporte'],['66&rsquor;|0:0|Abdessamad Ezzalzouli|for Sof...,['63&rsquor;|0:0|Álvaro Morata|for Marco Asens...,Oitavas de Final,Morocco,0,0,0,0
9,Portugal,Switzerland,6,2.3,NaN,1,1.2,NaN,Fernando Santos,Pepe,...,NaN,"['43&rsquor;|2:0|Fabian Schär', '59&rsquor;|4:...",['73&rsquor;|5:1|Cristiano Ronaldo|for Gonçalo...,['46&rsquor;|2:0|Eray Cömert|for Fabian Schär'...,Oitavas de Final,Portugal,0,0,0,0
10,Japan,Croatia,1,1.2,1.0,1,1.4,3.0,Hajime Moriyasu,Maya Yoshida,...,NaN,"['90&rsquor;|1:1|Mateo Kovačić', '116&rsquor;|...",['64&rsquor;|1:1|Takuma Asano|for Daizen Maeda...,['62&rsquor;|1:1|Ante Budimir|for Bruno Petkov...,Oitavas de Final,Croatia,0,0,0,0
11,Brazil,Korea Republic,4,3.6,NaN,1,0.5,NaN,Tite,Thiago Silva,...,NaN,['44&rsquor;|4:0|Jung Woo-young'],"['63&rsquor;|4:0|Dani Alves|for Éder Militão',...","['46&rsquor;|4:0|Hong Chul|for Kim Jin-su', '4...",Oitavas de Final,Brazil,0,0,0,0
12,France,Poland,3,1.4,NaN,1,1.7,NaN,Didier Deschamps,Hugo Lloris,...,['32&rsquor;|0:0|Aurélien Tchouaméni'],"['47&rsquor;|1:0|Bartosz Bereszyński', '88&rsq...",['66&rsquor;|1:0|Youssouf Fofana|for Aurélien ...,['64&rsquor;|1:0|Arkadiusz Milik|for Sebastian...,Oitavas de Final,France,0,0,0,0
13,England,Senegal,3,1.0,NaN,0,0.8,NaN,Gareth Southgate,Harry Kane,...,NaN,['76&rsquor;|3:0|Kalidou Koulibaly'],['65&rsquor;|3:0|Jack Grealish|for Phil Foden'...,['46&rsquor;|2:0|Pape Matar Sarr|for Krépin Di...,Oitavas de Final,England,0,0,0,0
14,Netherlands,United States,3,1.7,NaN,1,1.5,NaN,Louis van Gaal,Virgil van Dijk,...,"['60&rsquor;|2:0|Teun Koopmeiners', '87&rsquor...",NaN,['46&rsquor;|2:0|Teun Koopmeiners|for Davy Kla...,['46&rsquor;|2:0|Gio Reyna|for Jesús Ferreira'...,Oitavas de Final,Netherlands,0,0,0,0
15,Argentina,Australia,2,1.6,NaN,1,0.6,NaN,Lionel Scaloni,Lionel Messi,...,NaN,"['15&rsquor;|0:0|Jackson Irvine', '38&rsquor;|...",['50&rsquor;|1:0|Lisandro Martínez|for Papu Gó...,['58&rsquor;|2:0|Craig Goodwin|for Riley McGre...,Oitavas de Final,Argentina,0,0,0,0
16,Korea Republic,Portugal,2,1.7,NaN,1,1.3,NaN,Sérgio Costa,Son Heung-min,...,"['36&rsquor;|1:1|Lee Kangin', '90+2&rsquor;|2:...",NaN,['66&rsquor;|1:1|Hwang Hee-chan|for Lee Jae-su...,['65&rsquor;|1:1|João Palhinha|for Matheus Nun...,Fase de Grupos,Korea Republic,0,0,0,0
17,Ghana,Uruguay,0,1.6,NaN,2,1.8,NaN,Otto Addo,André Ayew,...,"['86&rsquor;|0:2|Kamaldeen Sulemana', '90+9&rs...","['19&rsquor;|0:0|Darwin Núñez', '60&rsquor;|0:...",['46&rsquor;|0:2|Kamaldeen Sulemana|for Jordan...,['34&rsquor;|0:2|Matías Vecino|for Rodrigo Ben...,Fase de Grupos,Uruguay,0,0,0,0
18,Cameroon,Brazil,1,0.5,NaN,0,2.5,NaN,Rigobert Song,Vincent Aboubakar,...,"['6&rsquor;|0:0|Nouhou Tolo', '28&rsquor;|0:0|...","['7&rsquor;|0:0|Éder Militão', '85&rsquor;|0:0...",['64&rsquor;|0:0|Karl Toko Ekambi|for Bryan Mb...,"['55&rsquor;|0:0|Everton Ribeiro|for Rodrygo',...",Fase de Grupos,Cameroon,0,0,1,0
19,Serbia,Switzerland,2,1.3,NaN,3,2.7,NaN,Dragan Stojković,Dušan Tadić,...,"['47&rsquor;|2:2|Sergej Milinković-Savić', '56...","['15&rsquor;|0:0|Silvan Widmer', '34&rsquor;|1...",['55&rsquor;|2:3|Nemanja Gudelj|for Miloš Velj...,['68&rsquor;|2:3|Edimilson Fernandes|for Djibr...,Fase de Grupos,Switzerland,0,0,0,0
20,Canada,Morocco,1,1.4,NaN,2,0.5,NaN,John Herdman,Milan Borjan,...,"['7&rsquor;|0:1|Junior Hoilett', '26&rsquor;|0...",NaN,['60&rsquor;|1:2|Atiba Hutchinson|for Mark-Ant...,['65&rsquor;|1:2|Selim Amallah|for Abdelhamid ...,Fase de Grupos,Morocco,0,0,0,0
21,Croatia,Belgium,0,0.7,NaN,0,3.0,NaN,Zlatko Dalić,Luka Modrić,...,NaN,['67&rsquor;|0:0|Leander Dendoncker'],['64&rsquor;|0:0|Bruno Petković|for Marko Liva...,['46&rsquor;|0:0|Romelu Lukaku|for Dries Merte...,Fase de Grupos,Draw,0,0,0,0
22,Costa Rica,Germany,2,1.3,NaN,4,5.7,NaN,Luis Fernando Suárez,Keylor Navas,...,['77&rsquor;|2:2|Óscar Duarte'],NaN,['46&rsquor;|0:1|Youstin Salas|for Brandon Agu...,['46&rsquor;|0:1|Lukas Klostermann|for Leon Go...,Fase de Grupos,Germany,0,0,0,0
23,Japan,Spain,2,1.4,NaN,1,1.0,NaN,Hajime Moriyasu,Maya Yoshida,...,"['39&rsquor;|0:1|Ko Itakura', '44&rsquor;|0:1|...",NaN,['46&rsquor;|0:1|Ritsu Doan|for Takefusa Kubo'...,['46&rsquor;|0:1|Dani Carvajal|for César Azpil...,Fase de Grupos,Japan,0,0,0,0
24,Australia,Denmark,1,0.6,NaN,0,0.6,NaN,Graham Arnold,Mathew Ryan,...,"['4&rsquor;|0:0|Aziz Behich', '57&rsquor;|0:0|...",['75&rsquor;|1:0|Robert Skov'],['46&rsquor;|0:0|Keanu Baccus|for Craig Goodwi...,['46&rsquor;|0:0|Alexander Bah|for Rasmus Niss...,Fase de Grupos,Australia,0,0,0,0
25,Tunisia,France,1,0.5,NaN,0,0.8,NaN,Jalel Kadri,Wahbi Khazri,...,['28&rsquor;|0:0|Wajdi Kechrida'],NaN,['60&rsquor;|1:0|Issam Jebali|for Wahbi Khazri...,['63&rsquor;|1:0|William Saliba|for Raphaël Va...,Fase de Grupos,Tunisia,0,0,0,0
26,Saudi Arabia,Mexico,1,1.1,NaN,2,2.3,NaN,Hervé Renard,Salem Al-Dawsari,...,"['28&rsquor;|0:0|Saleh Al-Shehri', '34&rsquor;...",['16&rsquor;|0:0|Edson Álvarez'],['37&rsquor;|0:0|Riyadh Sharahili|for Ali Al-B...,['46&rsquor;|0:0|Uriel Antuna|for Alexis Vega'...,Fase de Grupos,Mexico,0,0,0,0
27,Poland,Argentina,0,0.3,NaN,2,3.5,NaN,Czesław Michniewicz,Robert Lewandowski,...,['78&rsquor;|0:2|Grzegorz Krychowiak'],['49&rsquor;|0:1|Marcos Acuña'],['46&rsquor;|0:0|Jakub Kamiński|for Przemysław...,['59&rsquor;|0:1|Leandro Paredes|for Ángel Di ...,Fase de Grupos,Argentina,0,0,0,0
28,Ecuador,Senegal,1,0.9,NaN,2,2.1,NaN,Gustavo Alfaro,Enner Valencia,...,NaN,['66&rsquor;|0:1|Idrissa Gana Gueye'],['46&rsquor;|0:1|Jeremy Sarmiento|for Alan Fra...,['75&rsquor;|1:2|Nampalys Mendy|for Pathé Ciss...,Fase de Grupos,Senegal,0,0,0,0
29,Netherlands,Qatar,2,1.6,NaN,0,0.1,NaN,Louis van Gaal,Virgil van Dijk,...,['52&rsquor;|2:0|Nathan Aké'],NaN,"['66&rsquor;|2:0|Vincent Janssen|for Memphis',...",['64&rsquor;|2:0|Karim Boudiaf|for Assim Madib...,Fase de Grupos,Netherlands,0,0,0,0
30,IR Iran,United States,0,0.4,NaN,1,1.2,NaN,Carlos Queiroz,Ehsan Hajsafi,...,"['77&rsquor;|0:1|Majid Hosseini', '83&rsquor;|...",['43&rsquor;|0:1|Tyler Adams'],['45+2&rsquor;|0:1|Ali Karimi|for Milad Mohamm...,['46&rsquor;|0:1|Brenden Aaronson|for Christia...,Fase de Grupos,United States,0,0,0,0
31,Wales,England,0,0.3,NaN,3,2.4,NaN,Rob Page,Gareth Bale,...,"['29&rsquor;|0:0|Daniel James', '61&rsquor;|0:...",NaN,['37&rsquor;|0:0|Connor Roberts|for Neco Willi...,['57&rsquor;|0:2|Trent Alexander-Arnold|for Ky...,Fase de Grupos,England,0,0,0,0
32,Cameroon,Serbia,3,2.2,NaN,3,1.9,NaN,Rigobert Song,Eric Maxim Choupo-Moting,...,"['24&rsquor;|0:0|Nicolas Nkoulou', '30&rsquor;...","['45+4&rsquor;|1:2|Luka Jović', '90+3&rsquor;|...",['55&rsquor;|1:3|Vincent Aboubakar|for Martin ...,['56&rsquor;|1:3|Stefan Mitrović|for Strahinja...,Fase de Grupos,Draw,0,0,0,0
33,Korea Republic,Ghana,2,1.8,NaN,3,1.6,NaN,Paulo Bento,Son Heung-min,...,"['27&rsquor;|0:1|Jung Woo-young', '77&rsquor;|...","['21&rsquor;|0:0|Daniel Amartey', '73&rsquor;|...",['46&rsquor;|0:2|Na Sang-ho|for Jeong Woo-yeon...,['78&rsquor;|2:3|Daniel Kyereh|for André Ayew'...,Fase de Grupos,Ghana,1,0,0,0
34,Brazil,Switzerland,1,1.0,NaN,0,0.3,NaN,Tite,Thiago Silva,...,['52&rsquor;|0:0|Fred'],['50&rsquor;|0:0|Fabian Rieder'],"['46&rsquor;|0:0|Rodrygo|for Lucas Paquetá', '...",['59&rsquor;|0:0|Edimilson Fernandes|for Ruben...,Fase de Grupos,Brazil,0,0,0,0

In [21]:
matches['total_goals'] = matches ['home_score'] + matches ['away_score']

In [27]:
matches_clean = matches [['home_team', 'away_team', 'home_score', 'away_score', 'home_penalty', 'away_penalty', 
                          'total_goals', 'Winner', 'Stage', 'Year', 'Date', 'Host', 'Venue', 'Attendance', 'home_red_cards', 'away_red_cards', 
                          'home_yellow_red_cards', 'away_yellow_red_cards']]

In [28]:
matches_clean.head(35)

,home_team,away_team,home_score,away_score,home_penalty,away_penalty,total_goals,Winner,Stage,Year,Date,Host,Venue,Attendance,home_red_cards,away_red_cards,home_yellow_red_cards,away_yellow_red_cards
0,Argentina,France,3,3,4.0,2.0,6,Argentina,Final,2022,2022-12-18,Qatar,"Lusail Iconic Stadium, Lusail",88966,0,0,0,0
1,Croatia,Morocco,2,1,NaN,NaN,3,Croatia,Terceiro Lugar,2022,2022-12-17,Qatar,"Khalifa International Stadium, Doha",44137,0,0,0,0
2,France,Morocco,2,0,NaN,NaN,2,France,Semi-finais,2022,2022-12-14,Qatar,"Al Bayt Stadium, Al Khor",68294,0,0,0,0
3,Argentina,Croatia,3,0,NaN,NaN,3,Argentina,Semi-finais,2022,2022-12-13,Qatar,"Lusail Iconic Stadium, Lusail",88966,0,0,0,0
4,Morocco,Portugal,1,0,NaN,NaN,1,Morocco,Quartas de Final,2022,2022-12-10,Qatar,"Al Thumama Stadium, ath-Thumāma",44198,0,0,1,0
5,England,France,1,2,NaN,NaN,3,France,Quartas de Final,2022,2022-12-10,Qatar,"Al Bayt Stadium, Al Khor",68895,0,0,0,0
6,Croatia,Brazil,1,1,4.0,2.0,2,Croatia,Quartas de Final,2022,2022-12-09,Qatar,"Education City Stadium, Doha",43893,0,0,0,0
7,Netherlands,Argentina,2,2,3.0,4.0,4,Argentina,Quartas de Final,2022,2022-12-09,Qatar,"Lusail Iconic Stadium, Lusail",88235,0,0,1,0
8,Morocco,Spain,0,0,3.0,0.0,0,Morocco,Oitavas de Final,2022,2022-12-06,Qatar,"Education City Stadium, Doha",44667,0,0,0,0
9,Portugal,Switzerland,6,1,NaN,NaN,7,Portugal,Oitavas de Final,2022,2022-12-06,Qatar,"Lusail Iconic Stadium, Lusail",83720,0,0,0,0
10,Japan,Croatia,1,1,1.0,3.0,2,Croatia,Oitavas de Final,2022,2022-12-05,Qatar,"Al Janoub Stadium, Al Wakrah",42523,0,0,0,0
11,Brazil,Korea Republic,4,1,NaN,NaN,5,Brazil,Oitavas de Final,2022,2022-12-05,Qatar,"Stadium 974, Doha",43847,0,0,0,0
12,France,Poland,3,1,NaN,NaN,4,France,Oitavas de Final,2022,2022-12-04,Qatar,"Al Thumama Stadium, ath-Thumāma",40989,0,0,0,0
13,England,Senegal,3,0,NaN,NaN,3,England,Oitavas de Final,2022,2022-12-04,Qatar,"Al Bayt Stadium, Al Khor",65985,0,0,0,0
14,Netherlands,United States,3,1,NaN,NaN,4,Netherlands,Oitavas de Final,2022,2022-12-03,Qatar,"Khalifa International Stadium, Doha",44846,0,0,0,0
15,Argentina,Australia,2,1,NaN,NaN,3,Argentina,Oitavas de Final,2022,2022-12-03,Qatar,"Ahmed bin Ali Stadium, Umm al-Afā'ī",45032,0,0,0,0
16,Korea Republic,Portugal,2,1,NaN,NaN,3,Korea Republic,Fase de Grupos,2022,2022-12-02,Qatar,"Education City Stadium, Doha",44097,0,0,0,0
17,Ghana,Uruguay,0,2,NaN,NaN,2,Uruguay,Fase de Grupos,2022,2022-12-02,Qatar,"Al Janoub Stadium, Al Wakrah",43443,0,0,0,0
18,Cameroon,Brazil,1,0,NaN,NaN,1,Cameroon,Fase de Grupos,2022,2022-12-02,Qatar,"Lusail Iconic Stadium, Lusail",85986,0,0,1,0
19,Serbia,Switzerland,2,3,NaN,NaN,5,Switzerland,Fase de Grupos,2022,2022-12-02,Qatar,"Stadium 974, Doha",41378,0,0,0,0
20,Canada,Morocco,1,2,NaN,NaN,3,Morocco,Fase de Grupos,2022,2022-12-01,Qatar,"Al Thumama Stadium, ath-Thumāma",43102,0,0,0,0
21,Croatia,Belgium,0,0,NaN,NaN,0,Draw,Fase de Grupos,2022,2022-12-01,Qatar,"Ahmed bin Ali Stadium, Umm al-Afā'ī",43984,0,0,0,0
22,Costa Rica,Germany,2,4,NaN,NaN,6,Germany,Fase de Grupos,2022,2022-12-01,Qatar,"Al Bayt Stadium, Al Khor",67054,0,0,0,0
23,Japan,Spain,2,1,NaN,NaN,3,Japan,Fase de Grupos,2022,2022-12-01,Qatar,"Khalifa International Stadium, Doha",44851,0,0,0,0
24,Australia,Denmark,1,0,NaN,NaN,1,Australia,Fase de Grupos,2022,2022-11-30,Qatar,"Al Janoub Stadium, Al Wakrah",41232,0,0,0,0
25,Tunisia,France,1,0,NaN,NaN,1,Tunisia,Fase de Grupos,2022,2022-11-30,Qatar,"Education City Stadium, Doha",43627,0,0,0,0
26,Saudi Arabia,Mexico,1,2,NaN,NaN,3,Mexico,Fase de Grupos,2022,2022-11-30,Qatar,"Lusail Iconic Stadium, Lusail",84985,0,0,0,0
27,Poland,Argentina,0,2,NaN,NaN,2,Argentina,Fase de Grupos,2022,2022-11-30,Qatar,"Stadium 974, Doha",44089,0,0,0,0
28,Ecuador,Senegal,1,2,NaN,NaN,3,Senegal,Fase de Grupos,2022,2022-11-29,Qatar,"Khalifa International Stadium, Doha",44569,0,0,0,0
29,Netherlands,Qatar,2,0,NaN,NaN,2,Netherlands,Fase de Grupos,2022,2022-11-29,Qatar,"Al Bayt Stadium, Al Khor",66784,0,0,0,0
30,IR Iran,United States,0,1,NaN,NaN,1,United States,Fase de Grupos,2022,2022-11-29,Qatar,"Al Thumama Stadium, ath-Thumāma",42127,0,0,0,0
31,Wales,England,0,3,NaN,NaN,3,England,Fase de Grupos,2022,2022-11-29,Qatar,"Ahmed bin Ali Stadium, Umm al-Afā'ī",44297,0,0,0,0
32,Cameroon,Serbia,3,3,NaN,NaN,6,Draw,Fase de Grupos,2022,2022-11-28,Qatar,"Al Janoub Stadium, Al Wakrah",39789,0,0,0,0
33,Korea Republic,Ghana,2,3,NaN,NaN,5,Ghana,Fase de Grupos,2022,2022-11-28,Qatar,"Education City Stadium, Doha",43983,1,0,0,0
34,Brazil,Switzerland,1,0,NaN,NaN,1,Brazil,Fase de Grupos,2022,2022-11-28,Qatar,"Stadium 974, Doha",43649,0,0,0,0

In [29]:
champions = pd.read_csv('data/world_cup.csv')

In [30]:
champions.head()

,Year,Host,Teams,Champion,Runner-Up,TopScorrer,Attendance,AttendanceAvg,Matches
0,2022,Qatar,32,Argentina,France,Kylian Mbappé - 8,3404252,53191,64
1,2018,Russia,32,France,Croatia,Harry Kane - 6,3031768,47371,64
2,2014,Brazil,32,Germany,Argentina,James Rodríguez - 6,3429873,53592,64
3,2010,South Africa,32,Spain,Netherlands,"Wesley Sneijder, Thomas Müller... - 5",3178856,49670,64
4,2006,Germany,32,Italy,France,Miroslav Klose - 5,3352605,52384,64

In [32]:
print(champions.shape)

(22, 9)

In [33]:
print(champions.isnull().sum())

Year             0
Host             0
Teams            0
Champion         0
Runner-Up        0
TopScorrer       0
Attendance       0
AttendanceAvg    0
Matches          0
dtype: int64

In [35]:
print(champions.dtypes)

Year             int64
Host               str
Teams            int64
Champion           str
Runner-Up          str
TopScorrer         str
Attendance       int64
AttendanceAvg    int64
Matches          int64
dtype: object

In [36]:
matches_clean.to_csv('matches_clean.csv', index=False)
champions.to_csv('world_cup.csv', index=False)

print("Exportado com sucesso!")

Exportado com sucesso!